name: CI — FastAPI tests

on:
  push:
    branches: ["main"]
    paths-ignore: ["README.md", "docs/**", ".vscode/**", ".env.example"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["README.md", "docs/**", ".vscode/**", ".env.example"]

env:
  PYTHON_VERSION: "3.12"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  lint:
    name: Lint API code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install uv
          uv sync
      - name: Run ruff
        run: ruff check .

  test:
    name: Test API code
    runs-on: ubuntu-latest
    needs: [lint]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install uv
          uv sync
      - name: Run tests
        run: pytest
